# Generated by Django 5.0 on 2024-03-19 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuizResult',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sid', models.CharField(max_length=15)),
                ('quiz_title', models.CharField(max_length=30)),
                ('quiz_score', models.IntegerField()),
                ('submit_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'quizresult_table',
            },
        ),
    ]
