# Generated by Django 5.0 on 2024-02-09 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facultyapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecontent',
            name='description',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='coursecontent',
            name='link',
            field=models.CharField(max_length=200),
        ),
    ]
