# Generated by Django 5.0 on 2024-03-14 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
        ('facultyapp', '0002_alter_coursequiz_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursequiz',
            name='faculty_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='adminapp.faculty'),
            preserve_default=False,
        ),
    ]
