# Generated by Django 5.0 on 2024-03-14 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facultyapp', '0003_coursequiz_faculty_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursequiz',
            name='faculty_id',
            field=models.CharField(max_length=10),
        ),
    ]
