# Generated by Django 5.0 on 2024-02-16 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facultyapp', '0003_facultycontent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FacultyContent',
        ),
    ]
