# Generated by Django 5.0 on 2024-03-14 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facultyapp', '0004_alter_coursequiz_faculty_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursequiz',
            name='faculty_id',
        ),
    ]
