# Generated by Django 5.0 on 2024-02-16 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facultyapp', '0004_delete_facultycontent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursecontent',
            old_name='contentimage',
            new_name='content',
        ),
        migrations.AddField(
            model_name='coursecontent',
            name='chapter_name',
            field=models.TextField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coursecontent',
            name='chapter_no',
            field=models.TextField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coursecontent',
            name='topic',
            field=models.TextField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
