# Generated by Django 5.0 on 2024-02-16 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facultyapp', '0005_rename_contentimage_coursecontent_content_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursecontent',
            old_name='content',
            new_name='contentimage',
        ),
    ]
