# Generated by Django 5.0 on 2024-02-16 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facultyapp', '0006_rename_content_coursecontent_contentimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursecontent',
            old_name='contentimage',
            new_name='content',
        ),
    ]
