# Generated by Django 5.0 on 2024-02-20 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facultyapp', '0009_uploadwork'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadWork',
        ),
    ]
