# Generated by Django 5.0 on 2024-02-22 04:01

import adminapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facultyapp', '0010_delete_uploadwork'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecontent',
            name='course_code',
            field=models.CharField(default=0, verbose_name=adminapp.models.Course),
            preserve_default=False,
        ),
    ]
