# Generated by Django 5.0 on 2024-02-22 10:25

import adminapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facultyapp', '0013_remove_coursecontent_course_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursecontent',
            name='course',
        ),
        migrations.AddField(
            model_name='coursecontent',
            name='course_code',
            field=models.CharField(default=0, max_length=50, verbose_name=adminapp.models.Course),
            preserve_default=False,
        ),
    ]
