# Generated by Django 5.0 on 2024-02-29 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facultyapp', '0018_coursecontent_course_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedWork',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('student_id', models.CharField(max_length=50)),
                ('student_name', models.CharField(max_length=100)),
                ('file_url', models.CharField(max_length=255)),
                ('file_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'uploaded_works',
            },
        ),
    ]
