# Generated by Django 5.0 on 2024-02-29 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facultyapp', '0019_uploadedwork'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadWork',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('student_id', models.CharField(max_length=15)),
                ('student_name', models.CharField(max_length=30)),
                ('uploded_file', models.FileField(upload_to='uploadedfile')),
            ],
            options={
                'db_table': 'uplodedwork_table',
            },
        ),
        migrations.DeleteModel(
            name='UploadedWork',
        ),
    ]
