# Generated by Django 5.0 on 2024-02-29 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facultyapp', '0020_uploadwork_delete_uploadedwork'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadwork',
            old_name='student_name',
            new_name='topic_name',
        ),
    ]
