# Generated by Django 5.0 on 2024-02-29 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facultyapp', '0021_rename_student_name_uploadwork_topic_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadwork',
            name='student_name',
            field=models.CharField(default=None, max_length=35),
            preserve_default=False,
        ),
    ]
