# Generated by Django 5.0 on 2024-02-29 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facultyapp', '0022_uploadwork_student_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadwork',
            name='student_name',
        ),
    ]
