# Generated by Django 5.0 on 2024-02-29 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facultyapp', '0024_remove_uploadwork_uploded_file_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadwork',
            old_name='uploaded_file',
            new_name='uploded_file',
        ),
    ]
