# Generated by Django 5.0 on 2024-02-29 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facultyapp', '0025_rename_uploaded_file_uploadwork_uploded_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadwork',
            name='chapter_no',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='uploadwork',
            name='uploded_file',
            field=models.FileField(upload_to='uploadwork/'),
        ),
    ]
