# Generated by Django 5.0 on 2024-02-29 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facultyapp', '0027_remove_uploadwork_chapter_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadwork',
            old_name='uploded_file',
            new_name='uploaded_file',
        ),
        migrations.AlterModelTable(
            name='uploadwork',
            table='uploadedwork_table',
        ),
    ]
