# Generated by Django 5.0 on 2024-02-29 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facultyapp', '0028_rename_uploded_file_uploadwork_uploaded_file_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadwork',
            old_name='uploaded_file',
            new_name='uploded_file',
        ),
        migrations.AlterModelTable(
            name='uploadwork',
            table='uplodedwork_table',
        ),
    ]
