# Generated by Django 5.0 on 2024-02-18 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0007_alter_facultycoursemapping_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='program',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
