# Generated by Django 5.0 on 2024-03-09 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0009_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='facultyid',
            field=models.BigIntegerField(default=0, unique=True),
            preserve_default=False,
        ),
    ]
